export const restaurantsDDummyData = [
	{
		image: '/assets/restaurants/restaurant1.png',
		name: 'Bukolarry',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant2.png',
		name: 'Folly Fem',
		rating: 4.0,
		numberFoRatings: 34,
		deliveryPrice: 500,
		deliveryTime: '15 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant3.png',
		name: 'Korede spag',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant4.png',
		name: 'Amala Palace',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant5.png',
		name: 'Sharwama spot',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant6.png',
		name: 'Ice Cream Spot',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
];