export const restaurantsDDummyData = [
	{
		image: '/assets/restaurants/restaurant1.png',
		name: 'Bukolarry',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant2.png',
		name: 'Bukolarry',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant3.png',
		name: 'Bukolarry',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant4.png',
		name: 'Bukolarry',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant5.png',
		name: 'Bukolarry',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
	{
		image: '/assets/restaurants/restaurant6.png',
		name: 'Bukolarry',
		rating: 4.2,
		numberFoRatings: 234,
		deliveryPrice: 600,
		deliveryTime: '25 - 30minss',
	},
];